services:
  client:
    build: .
    volumes:
      - clientvol:/clientdata
    networks:
      - my_shared_network
    ports:
      - "3001:3001"

volumes:
  clientvol:

networks:
  my_shared_network:
    driver: bridge
    external: true
